import re

SKILL_PATTERNS = [
    ("Python", [r"\bpython\b"]),
    ("TypeScript", [r"\btypescript\b"]),
    ("JavaScript", [r"\bjavascript\b"]),
    ("Node.js", [r"\bnode(?:\.js)?\b"]),
    ("React", [r"\breact\b"]),
    ("Vue.js", [r"\bvue(?:\.js)?\b"]),
    ("SASS", [r"\bsass\b", r"\bscss\b"]),
    ("FastAPI", [r"\bfastapi\b"]),
    (
        "Go",
        [
            r"\bgolang\b",
            r"\bgo programming\b",
            r"\bgo language\b",
            r"\bpython or go\b",
            r"\bgo for testing\b",
        ],
    ),
    ("Java", [r"\bjava\b"]),
    ("Spring Boot", [r"\bspring boot\b"]),
    ("PHP", [r"\bphp\b"]),
    ("C#", [r"(?<!\w)c#(?!\w)", r"\bc sharp\b"]),
    ("C++", [r"(?<!\w)c\+\+(?!\w)"]),
    ("SQL", [r"\bsql\b"]),
    ("PostgreSQL", [r"\bpostgres(?:ql)?\b"]),
    ("MySQL", [r"\bmysql\b"]),
    ("MongoDB", [r"\bmongodb\b"]),
    ("Redis", [r"\bredis\b"]),
    (
        "Production databases",
        [r"production (?:database|databases|dbs)", r"databases in production"],
    ),
    ("Database performance", [r"database performance", r"performance, scaling, and reliability"]),
    ("GraphQL", [r"\bgraphql\b"]),
    ("Docker", [r"\bdocker\b"]),
    (
        "Containerization",
        [r"\bcontaineri[sz]ed\b", r"\bcontaineri[sz]ation\b", r"container-based deployments?"],
    ),
    ("Kubernetes", [r"\bkubernetes\b", r"\bk8s\b"]),
    ("GCP", [r"\bgcp\b", r"google cloud"]),
    ("Cloud Run", [r"\bcloud run\b"]),
    ("AWS", [r"\baws\b", r"amazon web services"]),
    ("Azure", [r"\bazure\b"]),
    ("Cloud infrastructure", [r"cloud infrastructure", r"infrastructure backbone"]),
    ("Cloud compute", [r"major cloud platform[^.\n]*compute", r"cloud[^.\n]*compute"]),
    ("Compute-intensive workloads", [r"compute-intensive workloads?"]),
    ("Scientific simulation workloads", [r"scientific simulation workloads?"]),
    ("Climate tech", [r"climate tech"]),
    ("Sustainability", [r"\bsustainability\b", r"\bsustainable\b"]),
    ("Built environment", [r"built environment"]),
    ("Cloud storage", [r"\bstorage\b"]),
    ("Networking", [r"\bnetworking\b", r"network architecture"]),
    ("Network architecture", [r"network architecture"]),
    ("Wireless networking", [r"wireless networking", r"wireless performance"]),
    ("4G/LTE", [r"\b4g/lte\b", r"\blte\b"]),
    ("5G", [r"\b5g\b"]),
    ("Wi-Fi", [r"\bwi-?fi\b"]),
    ("Mobile Edge Computing", [r"mobile edge computing", r"\bmec\b"]),
    ("TCP/IP", [r"\btcp/ip\b"]),
    ("UDP", [r"\budp\b"]),
    ("WebRTC", [r"\bwebrtc\b"]),
    ("gRPC", [r"\bgrpc\b"]),
    ("MQTT", [r"\bmqtt\b"]),
    ("ROS2/DDS", [r"\bros2/dds\b", r"\bros2\b", r"\bdds\b"]),
    ("RF engineering", [r"\brf engineering\b", r"\brf\b"]),
    ("Antenna design", [r"antenna design"]),
    ("Link budget analysis", [r"link budget analysis"]),
    ("IAM", [r"\biam\b", r"identity and access management"]),
    ("Authentication", [r"\bauthentication\b"]),
    ("Encryption", [r"\bencryption\b"]),
    ("Secure message passing", [r"secure message-passing", r"secure message passing"]),
    ("TLS", [r"\btls\b", r"\bssl\b"]),
    ("Firewall rules", [r"firewall rules?", r"\bfirewalls?\b"]),
    ("RBAC", [r"\brbac\b", r"role-based access control"]),
    ("Job queues", [r"job queues?", r"\bqueues?\b"]),
    ("Distributed workloads", [r"distributed workloads?"]),
    ("Distributed systems", [r"distributed systems?"]),
    ("Large-scale distributed systems", [r"large-scale distributed systems?"]),
    ("Search engines", [r"search engines?"]),
    ("Elasticsearch", [r"\belasticsearch\b"]),
    ("OpenSearch", [r"\bopensearch\b"]),
    ("Apache Solr", [r"apache solr", r"\bsolr\b"]),
    ("Apache Lucene", [r"apache lucene", r"\blucene\b"]),
    ("Event-driven architecture", [r"event-driven"]),
    ("Event-based analytics", [r"event-based analytics"]),
    ("A/B testing", [r"\ba/b (?:testing|experiments?)\b"]),
    ("Hypothesis building", [r"hypothesis building"]),
    ("Metrics", [r"\bmetrics\b"]),
    ("CI/CD pipelines", [r"\bci/cd\b", r"continuous integration", r"continuous deployment"]),
    ("GitHub Actions", [r"github actions"]),
    ("GitLab CI", [r"gitlab ci"]),
    ("Jenkins", [r"\bjenkins\b"]),
    ("Release management", [r"release process", r"release management", r"production deployment"]),
    ("Deployment workflows", [r"deployment workflows?", r"deployment process"]),
    ("Rollbacks", [r"\brollbacks?\b"]),
    ("Staging environments", [r"\bstaging\b"]),
    ("QA", [r"\bqa\b", r"quality assurance"]),
    ("E2E tests", [r"\be2e tests?\b", r"end-to-end tests?"]),
    ("Integration tests", [r"integration tests?"]),
    ("Developer experience", [r"developer experience", r"\bdx\b"]),
    ("On-call", [r"on-call", r"on call"]),
    ("Incident response", [r"incident response", r"severity processes?"]),
    ("Reliability engineering", [r"\breliability\b", r"ensure uptime", r"stable releases?"]),
    ("Observability", [r"\bobservability\b", r"\bobservable systems?\b"]),
    ("Monitoring", [r"\bmonitoring\b"]),
    ("Vulnerability scanning", [r"vulnerability scanning"]),
    ("Penetration testing", [r"penetration testing", r"\bpentest(?:ing)?\b"]),
    ("Infrastructure hardening", [r"infrastructure hardening", r"security hardening"]),
    ("Infrastructure engineering", [r"infrastructure engineering"]),
    ("Platform engineering", [r"platform engineering"]),
    ("Backend engineering", [r"backend engineering", r"backend codebase"]),
    ("Full-stack engineering", [r"full stack", r"full-stack"]),
    ("Frontend frameworks", [r"frontend application frameworks?", r"component-based frontend"]),
    ("Data-oriented codebases", [r"data-oriented codebases?"]),
    ("Terraform", [r"\bterraform\b"]),
    ("Infrastructure as Code", [r"infrastructure-as-code", r"infrastructure as code", r"\biac\b"]),
    ("Ansible", [r"\bansible\b"]),
    ("Pulumi", [r"\bpulumi\b"]),
    ("Kafka", [r"\bkafka\b"]),
    ("RabbitMQ", [r"\brabbitmq\b"]),
    ("Airflow", [r"\bairflow\b"]),
    ("Dagster", [r"\bdagster\b"]),
    ("MLflow", [r"\bmlflow\b"]),
    ("Machine Learning", [r"\bmachine learning\b", r"\bml\b"]),
    ("Deep Learning", [r"\bdeep learning\b"]),
    ("GenAI", [r"\bgenai\b", r"generative ai"]),
    ("LLMs", [r"\bllms?\b", r"large language models?"]),
    ("RAG", [r"\brag\b", r"retrieval augmented generation"]),
    ("Multi-agent systems", [r"multi-agent systems?", r"multi agent systems?"]),
    ("Text2SQL", [r"\btext2sql\b", r"text-to-sql"]),
    ("Fine-tuning", [r"\bfine-tun(?:e|ing)\b", r"\bfinetun(?:e|ing)\b"]),
    ("LangChain", [r"\blangchain\b"]),
    ("DSPy", [r"\bdspy\b"]),
    ("Hugging Face", [r"hugging ?face"]),
    ("AI/ML models", [r"\bai/ml models?\b", r"\bai models?\b", r"\bml models?\b"]),
    ("Model evaluation", [r"\bmodel evaluation\b", r"\bevaluating models?\b"]),
    ("PyTorch", [r"\bpytorch\b"]),
    ("TensorFlow", [r"\btensorflow\b"]),
    ("scikit-learn", [r"scikit-learn", r"\bsklearn\b"]),
    ("NumPy", [r"\bnumpy\b"]),
    ("pandas", [r"\bpandas\b"]),
    ("Apache Spark", [r"apache spark", r"\bspark\b"]),
    ("Databricks", [r"\bdatabricks\b"]),
    ("Data engineering", [r"\bdata engineering\b"]),
    ("Analytics engineering", [r"\banalytics engineering\b"]),
    ("Linux", [r"\blinux(?:-based)?\b"]),
    ("Robotics", [r"\brobotics\b", r"\brobotic\b"]),
    ("Autonomous vehicles", [r"autonomous vehicles?"]),
    ("Drones", [r"\bdrones?\b"]),
    ("Teleoperation", [r"\bteleoperation\b"]),
    ("Remote supervision", [r"remote supervision"]),
    ("Middleware integration", [r"middleware integration"]),
    ("Cloud-to-edge architecture", [r"cloud-to-edge architectures?"]),
    ("E-commerce", [r"\be-?commerce\b"]),
    ("Stakeholder management", [r"manage stakeholders?", r"stakeholder management"]),
    ("Communication", [r"communication skills?", r"written and verbal communication"]),
    ("Collaboration", [r"collaboration skills?", r"cross-functional"]),
    ("Mentoring", [r"\bmentor(?:ing)?\b"]),
    ("Hiring", [r"\btechnical hiring\b", r"\binterviewing candidates\b", r"\bhiring plans?\b"]),
]

SKILL_KEYWORDS = [name for name, _patterns in SKILL_PATTERNS]

MUST_HAVE_SECTION_STARTS = (
    "must have",
    "must-have",
    "requirements",
    "your toolkit",
    "who we are looking for",
    "what we look for",
    "what you must have",
    "what you'll need",
    "what you will need",
    "what should you bring along",
    "what you bring along",
    "qualifications",
    "your profile",
    "anforderungen",
    "profil",
    "was du mitbringst",
)

NICE_TO_HAVE_SECTION_STARTS = (
    "nice to have",
    "nice-to-have",
    "preferred",
    "bonus",
    "bonus points",
    "get some bonus points",
    "extras that give you an edge",
    "plus",
    "wunschenswert",
    "wünschenswert",
)

REQUIREMENT_SECTION_STOPS = (
    "nice to have",
    "nice-to-have",
    "preferred",
    "bonus",
    "extras that give you an edge",
    "benefits",
    "what we offer",
    "what do we offer",
    "how we'll make",
    "how we'll make",
    "how to apply",
    "start date",
    "type of employment",
    "working hours",
    "about ",
    "show more",
    "seniority level",
    "employment type",
    "job function",
    "industries",
)

SENIORITY_KEYWORDS = {
    "senior": "Senior",
    "lead": "Lead",
    "principal": "Principal",
    "staff": "Staff",
    "junior": "Junior",
    "graduate": "Graduate",
    "intern": "Intern",
    "head of": "Head",
    "manager": "Manager",
    "director": "Director",
    "vp": "VP",
    "chief": "Chief",
}

WORK_MODEL_KEYWORDS = {
    "remote": "remote",
    "fully remote": "remote",
    "100% remote": "remote",
    "hybrid": "hybrid",
    "onsite": "onsite",
    "on-site": "onsite",
    "in office": "onsite",
}

DACH_CITIES = [
    "berlin",
    "munich",
    "hamburg",
    "cologne",
    "frankfurt",
    "stuttgart",
    "düsseldorf",
    "leipzig",
    "dresden",
    "bonn",
    "zurich",
    "geneva",
    "bern",
    "basel",
    "lausanne",
    "vienna",
    "salzburg",
    "graz",
    "linz",
]

DACH_COUNTRIES = ["germany", "switzerland", "austria", "deutschland"]

GERMAN_KEYWORDS = [
    "german",
    "deutsch",
    "deutschkenntnisse",
    "fließend deutsch",
    "verhandlungssicher",
    "muttersprache",
]

SWISS_LOCATION_KEYWORDS = [
    "switzerland",
    "swiss",
    "schweiz",
    "suisse",
    "svizzera",
    "zurich",
    "zürich",
    "zuerich",
    "geneva",
    "basel",
    "bern",
    "lausanne",
]

STRICT_WORK_AUTH_PATTERNS = [
    r"\b(?:only|must|require[sd]?|eligible|eligibility|applicants?|candidates?)\b.{0,140}\b(?:swiss|switzerland|schweiz|eu|e/u|efta|european union|swedish|sweden)\b.{0,140}\b(?:citizenship|citizens?|passport|work permit|right to work|work authori[sz]ation|eligible)\b",
    r"\b(?:swiss|switzerland|schweiz|eu|e/u|efta|european union|swedish|sweden)\b.{0,80}\b(?:citizenship|citizens?|passport holders?|work permit|right to work)\b.{0,80}\b(?:only|required|must|can't|cannot|unable|unfortunately)\b",
    r"\b(?:valid|existing)\b.{0,60}\b(?:swiss|switzerland|schweiz|eu|efta)\b.{0,60}\b(?:work permit|work authori[sz]ation|right to work)\b",
    r"\b(?:can't|cannot|unable to|unfortunately)\b.{0,120}\b(?:support|sponsor)\b.{0,120}\bnon[-\s]?eu\b",
]

VISA_SPONSORSHIP_WARNING_PATTERNS = [
    r"\b(?:no|not|unable to|cannot)\b.{0,80}\b(?:visa sponsorship|sponsor visas?|work permit sponsorship)\b",
    r"\b(?:must|need to)\b.{0,80}\b(?:already|currently)\b.{0,80}\b(?:authorized|eligible|right to work)\b",
]

SKILL_CITY_BLACKLIST: set[str] = {
    "amsterdam",
    "athens",
    "atlanta",
    "austin",
    "bangalore",
    "bangkok",
    "barcelona",
    "beijing",
    "berlin",
    "boston",
    "brussels",
    "budapest",
    "buenos aires",
    "chicago",
    "copenhagen",
    "dallas",
    "denver",
    "dubai",
    "dublin",
    "edinburgh",
    "frankfurt",
    "geneva",
    "hamburg",
    "helsinki",
    "hong kong",
    "istanbul",
    "jakarta",
    "lisbon",
    "london",
    "los angeles",
    "madrid",
    "manchester",
    "melbourne",
    "mexico city",
    "miami",
    "milan",
    "montreal",
    "moscow",
    "mumbai",
    "munich",
    "new orleans",
    "new york",
    "oslo",
    "paris",
    "prague",
    "riga",
    "rio de janeiro",
    "rome",
    "san francisco",
    "santiago",
    "sao paulo",
    "seattle",
    "seoul",
    "shanghai",
    "singapore",
    "stockholm",
    "sydney",
    "tallinn",
    "tel aviv",
    "tokyo",
    "toronto",
    "vancouver",
    "vienna",
    "vilnius",
    "warsaw",
    "zurich",
    "basel",
    "bern",
    "lausanne",
}

SKILL_SPLIT_RE = re.compile(r"\s*(?:,|;|\bor\b|\band\b)\s*", flags=re.IGNORECASE)
SKILL_LIST_TRIGGER_RE = re.compile(
    r"(?:such as|including|include|includes|like|for example|e\.g\.|frameworks? like|tools? such as)\s+([^.\n]+)",
    flags=re.IGNORECASE,
)

SKILL_NAME_ALIASES = {
    "huggingface": "Hugging Face",
    "node": "Node.js",
    "nodejs": "Node.js",
    "vue": "Vue.js",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "k8s": "Kubernetes",
    "ci/cd": "CI/CD pipelines",
    "mec": "Mobile Edge Computing",
    "ros2": "ROS2/DDS",
    "dds": "ROS2/DDS",
    "grpc": "gRPC",
    "webrtc": "WebRTC",
    "mqtt": "MQTT",
    "tcp/ip": "TCP/IP",
    "wifi": "Wi-Fi",
    "wi-fi": "Wi-Fi",
    "node.js": "Node.js",
    "langchain": "LangChain",
    "dspy": "DSPy",
    "sklearn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "numpy": "NumPy",
    "pandas": "pandas",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "rag": "RAG",
    "llm": "LLMs",
    "llms": "LLMs",
    "text2sql": "Text2SQL",
    "genai": "GenAI",
}

def _dedupe_preserve_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        cleaned = str(item).strip()
        if not cleaned:
            continue
        key = re.sub(r"\s+", " ", cleaned).strip(" .;:").casefold()
        if key in seen:
            continue
        seen.add(key)
        result.append(cleaned)
    return result


NON_SKILL_CANDIDATES = {
    "etc",
    "similar",
    "similar systems",
    "and more",
    "more",
    "all levels",
    "the form below",
    "benchmark",
    "engineering",
    "index ventures",
    "ivp",
    "it architects",
    "christmas bonus",
    "vacation pay",
    "profit sharing",
    "6 weeks annual leave",
}
