# ===========================================================================
# Core
# ===========================================================================
variable "name_prefix" {
  description = "Prefix for all AWS resource names"
  type        = string
  default     = "dachjob-dev"
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "eu-west-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

# ===========================================================================
# Database
# ===========================================================================
variable "db_password" {
  description = "PostgreSQL master password (auto-generated by Secrets Manager if empty)"
  type        = string
  sensitive   = true
  default     = ""
}

# ===========================================================================
# Container Images
# ===========================================================================
variable "api_image_tag" {
  description = "Docker image tag for the API"
  type        = string
  default     = "latest"
}

variable "frontend_image_tag" {
  description = "Docker image tag for the frontend"
  type        = string
  default     = "latest"
}

variable "worker_image_tag" {
  description = "Docker image tag for the worker"
  type        = string
  default     = "latest"
}

# ===========================================================================
# ECS Scaling
# ===========================================================================
variable "api_cpu" {
  description = "CPU units for API task"
  type        = number
  default     = 512
}

variable "api_memory" {
  description = "Memory (MiB) for API task"
  type        = number
  default     = 1024
}

variable "frontend_cpu" {
  description = "CPU units for frontend task"
  type        = number
  default     = 512
}

variable "frontend_memory" {
  description = "Memory (MiB) for frontend task"
  type        = number
  default     = 1024
}

variable "worker_cpu" {
  description = "CPU units for worker task"
  type        = number
  default     = 512
}

variable "worker_memory" {
  description = "Memory (MiB) for worker task"
  type        = number
  default     = 1024
}

variable "api_desired_count" {
  description = "Desired task count for API"
  type        = number
  default     = 1
}

variable "frontend_desired_count" {
  description = "Desired task count for frontend"
  type        = number
  default     = 1
}

variable "worker_desired_count" {
  description = "Desired task count for worker (0 = disabled)"
  type        = number
  default     = 0
}

variable "worker_enabled" {
  description = "Enable Celery worker (WORKER_ENABLED env var)"
  type        = string
  default     = "false"
}

# ===========================================================================
# Application
# ===========================================================================
variable "redis_enabled" {
  description = "Enable Redis at runtime"
  type        = bool
  default     = true
}

variable "cors_origins" {
  description = "CORS allowed origins"
  type        = string
  default     = ""
}

variable "llm_provider" {
  description = "LLM provider"
  type        = string
  default     = "deepseek"
}

variable "resend_from_email" {
  description = "Sender email for Resend"
  type        = string
  default     = "onboarding@resend.dev"
}

# ===========================================================================
# CloudFront
# ===========================================================================
variable "cloudfront_domain" {
  description = "CloudFront distribution domain name (e.g., d123.cloudfront.net). Leave empty if not using CloudFront."
  type        = string
  default     = "d3ktpumdo7sly4.cloudfront.net"
}

# ===========================================================================
# GitHub OIDC
# ===========================================================================
variable "github_repo" {
  description = "GitHub repository in owner/repo format for OIDC trust"
  type        = string
  default     = "BladeRunnerYao/dachjob.ai"
}

# ===========================================================================
# Tags
# ===========================================================================
variable "tags" {
  description = "Tags applied to all resources"
  type        = map(string)
  default = {
    environment = "dev"
    managed_by  = "terraform"
    project     = "dachjob"
  }
}
